# Generated by Django 3.0.7 on 2020-06-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.CharField(max_length=8),
        ),
    ]
